name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    env:
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_COMPRESS: "true"
      CCACHE_DIR: ${{ github.workspace }}/.cache/ccache
      CCACHE_MAXSIZE: 2G
      UV_CACHE_DIR: ${{ github.workspace }}/.cache/uv
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # TODO: ubuntu-latest, ubuntu-24.04-arm, macos-13
        os: [macos-14]

    steps:
      # Checkout
      - uses: actions/checkout@v5

      # Nix
      - uses: DeterminateSystems/nix-installer-action@main
        name: Setup - Nix
      - uses: DeterminateSystems/magic-nix-cache-action@main
        name: Setup - Magic Nix cache

      # A few brew deps (to appease ClickHouse...)
      - name: Setup - MacOS
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: brew install findutils grep

      # Caching
      - uses: actions/cache@v4
        with:
          path: |
            .cache/ccache
            .cache/uv
            tmp/ClickHouse
          key: ${{ runner.os }}-cache-${{ hashFiles('flake.nix', 'flake.lock', 'Justfile') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      # Build
      - name: 🔧 Fetch ClickHouse
        run: nix develop --command bash -c 'just fetch-clickhouse'

      # While debugging, run the build command directly
      - name: 🔧 Build
        run: nix develop --command bash -c 'just build'

      # - name: 🔧 Build wheels
      #   run: nix develop --command bash -c 'just build-ci'

      # Uploads
      # TODO: Only do this on PR builds and main branch
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
